(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["Fishers`FoMSWG`"];

readFisher::usage = "readFisher[fn] reads in a FoMSWG fisher matrix.
WARNING! This routine may be a little brittle.";
aFoMSWG::usage = "aFoMSWG[i] is scale factor defined by FoMSWG; 0 <= i < 36";

Begin["`Private`"];

aFoMSWG[i_/;(IntegerQ[i] && i>=0 && i<36)] := 1.0 - 0.025i - 0.0125;

readFisher[fn_] := Module[{arr, rl}, 
	arr = Import[fn, "Table"];
	(* Mathematica is 1-indexed *)
	arr ={#1+1, #2 + 1, #3} & @@@ arr;
	(* Parse into sparse array rules *)
	rl = If[
		#1 == #2, 
		{#1,#2}-> #3, 
		{{#1,#2}-> #3, {#2,#1}-> #3}
		] & @@@ arr;
	Normal[SparseArray[Flatten[rl]]]
	];

End[];
EndPackage[];


