(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["Cosmology`MassFunction`"]

(* Needs statements go here *)
Needs["Cosmology`Defs`"]

(* You should put usage statements here *)
deltac::usage = "deltac is the spherical collapse overdensity at z=0"
ShethTormen::usage = "ShethTormen[v] is the Sheth-Tormen multiplicity function"
PressSchechter::usage = "PressSchechter[v] is the PS multiplicity function"

(* The private section of the package is here *)
Begin["`Private`"]

deltac = 1.686;

(* Generic functional form *)
vfv[v_] := norm*(1 + (a*v^2)^(-p)) * Exp[- a*v^2/2] / Sqrt[a];
ShethTormen[v_] := vfv[v] /. {a -> 0.707, p-> 0.3, norm-> 1/(2*5.50221)};
PressSchechter[v_] := vfv[v]/.{a->1, p->0, norm-> 1/Sqrt[8 Pi]};

End[]
EndPackage[]


